### ISSUE TITLE
Printing files with error at the end is needed

### ISSUE THREAD

**Issue by maxonfjvipon** [yegor256/copyrights-action#49]
I'm getting this:
<img width="498" alt="image" src="https://github.com/user-attachments/assets/c9f4e7a8-5b8d-4e9b-81f8-3ff5ccc8c215">

So it's unclear which file has an error, I need to scroll all the 1082 lines and try to find which file is wrong. It would be nice if such file is printed at the end.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.7`

**Comment by yegor256** [comment]
@maxonfjvipon fixed, try version 0.0.8
